//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tiệm_nét
{
    using System;
    using System.Collections.Generic;
    
    public partial class Khachhang
    {
        public Khachhang()
        {
            this.Hoadons = new HashSet<Hoadon>();
            this.Hoadon_thucan = new HashSet<Hoadon_thucan>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        public string Phone { get; set; }
        public int Id_maytinh { get; set; }
        public int Id_phongmay { get; set; }
    
        public virtual ICollection<Hoadon> Hoadons { get; set; }
        public virtual ICollection<Hoadon_thucan> Hoadon_thucan { get; set; }
        public virtual Maytinh Maytinh { get; set; }
    }
}
