//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tiệm_nét
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phongmay
    {
        public Phongmay()
        {
            this.Maytinhs = new HashSet<Maytinh>();
        }
    
        public int Id { get; set; }
        public string Typed { get; set; }
        public int Count { get; set; }
        public int Id_chinhanh { get; set; }
    
        public virtual Chinhanh Chinhanh { get; set; }
        public virtual ICollection<Maytinh> Maytinhs { get; set; }
    }
}
