//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tiệm_nét
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chitiet_hoadon
    {
        public int Id_thucan { get; set; }
        public int Id_hoadon { get; set; }
        public int Count { get; set; }
        public int Total { get; set; }
    
        public virtual Hoadon_thucan Hoadon_thucan { get; set; }
        public virtual Thucan Thucan { get; set; }
    }
}
