//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tiệm_nét
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chinhanh
    {
        public Chinhanh()
        {
            this.Nhanviens = new HashSet<Nhanvien>();
            this.Phongmays = new HashSet<Phongmay>();
        }
    
        public int Id { get; set; }
        public string Chinhanh1 { get; set; }
        public int Id_district { get; set; }
    
        public virtual District District { get; set; }
        public virtual ICollection<Nhanvien> Nhanviens { get; set; }
        public virtual ICollection<Phongmay> Phongmays { get; set; }
    }
}
