//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tiệm_nét
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nhanvien
    {
        public Nhanvien()
        {
            this.Hoadons = new HashSet<Hoadon>();
            this.Hoadon_thucan = new HashSet<Hoadon_thucan>();
            this.Nhanvien1 = new HashSet<Nhanvien>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int Id_Manager { get; set; }
        public string Gender { get; set; }
        public string Address { get; set; }
        public int Id_chinhanh { get; set; }
    
        public virtual Chinhanh Chinhanh { get; set; }
        public virtual ICollection<Hoadon> Hoadons { get; set; }
        public virtual ICollection<Hoadon_thucan> Hoadon_thucan { get; set; }
        public virtual ICollection<Nhanvien> Nhanvien1 { get; set; }
        public virtual Nhanvien Nhanvien2 { get; set; }
    }
}
